### ISSUE TITLE
[Feature Request] Make Repository Selector Searchable

### ISSUE THREAD

**Issue by asadislam94** [BlueBasher/easy-branch-creator#1]
Could we use "azure-devops-ui/EditableDropdown" instead of "azure-devops-ui/Dropdown"?
As far as I know it is a direct replacement and should work but I am not really good at typescript and am unable to test it.

Making it Searchable is usefull when you have too many repositories and this should make it so.

**Comment by BlueBasher** [comment]
Making the repositories searchable somehow is indeed one of the features I wanted to add as well.
I'll try to have a look this weekend to see if it's doable using the EditableDropdown.

**Comment by BlueBasher** [comment]
This is now implemented in #2 and is available in version 0.1.44
