### ISSUE TITLE
Can not list custom WotkItem Types under Template Overrides.

### ISSUE THREAD

**Issue by bilgicalpay** [BlueBasher/easy-branch-creator#14]
in settings page we cant select custom WorkItem under Template Overrides.

Description: I was edited Process Templates as Scrum and Add 2 workitem type. Names are Hotfix and Pipeline. I want to create branch via Hotfix Workitem type then will create branch "hotfix/${System.Id}-${System.Title}". Same again create branch  Pipeline workitemType  Create Branch "feature/${System.Id}-${System.Title}

Best Regards.

**Comment by BlueBasher** [comment]
This should work. As you can see in the readme.md under Settings section, I also have custom workitem types (example Live Site Incident).
Could it be some caching or some other permission issue?
