### ISSUE TITLE
List the possible template variables

### ISSUE THREAD

**Issue by bp612** [BlueBasher/easy-branch-creator#24]
What are the possible variables we can use in the Template name?  The example shows two (`${System.ID} and ${System.Title}`).  I can't find a list anywhere of what other variables are supported.  You should include either a list or some references where we can find other variables.

**Comment by BlueBasher** [comment]
The values that you can use are all the Work Item Fields that are available in your project. That differs per Azure DevOps Organization so I can not make a generic list. If someone has custom fields, they can also be used.
If you want to see all the fields available to you, you can use this API: https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/work-item-types-field/list?view=azure-devops-rest-7.1&tabs=HTTP
